version: '3'
volumes:
  data:
services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7.18
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=development
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1