services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7.18
    container_name: docker_mysql
    networks:
      - development-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=development
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker_phpmyadmin
    networks:
      - development-network
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
networks:
  development-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
